{% set version = '0.4-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-classint
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/classInt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/classInt/classInt_{{ version }}.tar.gz
  sha256: 39c63f8e37b379033d73d57929b5b8ea41b0023626cc1cec648d66bade5d0103

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-kernsmooth
    - r-class
    - r-e1071
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-kernsmooth
    - r-class
    - r-e1071

test:
  commands:
    - $R -e "library('classInt')"           # [not win]
    - "\"%R%\" -e \"library('classInt')\""  # [win]

about:
  home: https://github.com/r-spatial/classInt/
  license: GPL-2
  summary: Selected commonly used methods for choosing univariate class intervals for mapping
    or other graphics purposes.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: classInt
# Version: 0.4-1
# Date: 2019-07-22
# Title: Choose Univariate Class Intervals
# Authors@R: c(person("Roger", "Bivand", role=c("aut", "cre"), email="Roger.Bivand@nhh.no", comment=c(ORCID="0000-0003-2392-6140")), person("Hisaji", "Ono", role="ctb"), person("Richard", "Dunlap", role="ctb"), person("Matthieu", "Stigler", role="ctb"))
# Depends: R (>= 2.2)
# Imports: grDevices, stats, graphics, e1071, class, KernSmooth
# Suggests: spData (>= 0.2.6.2), units
# NeedsCompilation: yes
# Description: Selected commonly used methods for choosing univariate class intervals for mapping or other graphics purposes.
# License: GPL (>= 2)
# URL: https://github.com/r-spatial/classInt/
# BugReports: https://github.com/r-spatial/classInt/issues/
# RoxygenNote: 6.1.1
# Packaged: 2019-08-06 07:15:26 UTC; rsb
# Author: Roger Bivand [aut, cre] (<https://orcid.org/0000-0003-2392-6140>), Hisaji Ono [ctb], Richard Dunlap [ctb], Matthieu Stigler [ctb]
# Maintainer: Roger Bivand <Roger.Bivand@nhh.no>
# Repository: CRAN
# Date/Publication: 2019-08-06 09:00:05 UTC
