{% set version = '0.2-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-classint
  version: {{ version|replace("-", "_") }}

source:
  fn: classInt_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/classInt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/classInt/classInt_{{ version }}.tar.gz
  sha256: 21f447330ce7eb6f069f48cacc4bca7d14521218463ecb74f1b3df5ddae0d1a9

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-class
    - r-e1071
    - r-spdata >=0.2.6.2
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-class
    - r-e1071
    - r-spdata >=0.2.6.2

test:
  commands:
    - $R -e "library('classInt')"           # [not win]
    - "\"%R%\" -e \"library('classInt')\""  # [win]

about:
  home: https://github.com/r-spatial/classInt/
  license: GPL (>= 2)
  summary: Selected commonly used methods for choosing univariate class intervals for mapping
    or other graphics purposes.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - ocefpaf
