travis:
  secure:
    BINSTAR_TOKEN: Zpqc4VWHFxsE37bvZ2/0QZ5HBNd+MUOjnEubgsltZD6VDKEePeh+MQuQCxsZkrgq7yaUjSqWuCik/XTk060CzjQF1yrG/Yt/aHUGe4fzzF1oXaGffvEb7ZGJrefDeF7T+nSWAW+ASxe6oykOjK30zXmk1OV7HhVkgM5t5A6QJeBU75tqN83U/uIJtyETFEINv1IkZhjbSJwJ+WM1JrqLMhFcef6QcVhQJjEcgiIn5jJyEJk3WlNvJDZd0Z9UNRKp1t7dW4ZDfyeICKsF6UUaUXoJnKYhnKSI4egP6xxNekXRFdMv4yiLwxbidxKudyjloWuEs3AYNT1S0DH72lSD9kvOvgChadArhx5UDQTSJi5OIn6BBy2WbwDZ31+mUQCoFz3lr3yhI2oJSpqec2qy0cB1rEEp4D6hGBMKlseGYykaxLeqBxFf8hzwCTV52661H6RZcWhCoUyuSAkBsTVkAqkfdWbW2tLrrP8Rh8NeRFHicW9uDM7/+jYQ70RmyBHZxk0UqEfZlxJZFTzFzHe8X6SvFpvpQX8BFxcd0MxiTldBO1OmgX5cBLXODBYWY0aXjrPCCmlP5rPUgZ/7vnluGDS9uWiEUDPfy6+P3mNDDacWJ1OerVYnI3PBDkaqtg/6yh9J93bWyvDEWOgQ3c9frdedcn19uWQoIG4zZuXQY0I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
