appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
bot: {automerge: true}
provider: {linux_aarch64: default, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: c5Ke3EDUpGKpdlFs33H9wF9dq9ceT35Yhy2ct94CO+r4meHgrxW7LnhQkaRXYemINKqZ6F2IRHXTvbRYMNlUOgIn01yLnpvwj+KeoOaY8J1w4GsJABLSf1Bdz0tkkq9N3LXq4jIgHzLZJ2CAuVrZyo+PPDcDUk31fmYyk6QLz/vSkmyTieddrmLeZQ4on+USmk+PJUGzOGRlBZug2tzAf0J9nJnz61XB3Fq/SH7azCprF8y1FXk9CMLpi6CrQzHtOROUtM6tPd0awT5hVb+dd78ZxzOJy5vAthT4aLgsF1YWEd9X0HZYia8auRk//8DoIi2w+Gt7ETnxcX/bwwBs/ktuqLFGX872Pu3Ilqnkqf4jTaD2I9TzaCQBd+vWZXMCTaBls6NUryssLFNIzG6hPPyNConsX7QN9+zqhR3iAYFpDjnk1OjIfpwtSVTb5YZRkY6jMW+LxeogU2LVj2eI0BWNFxQLnSK8A2GXhJjqKEOr2C+Uk28F3KZqxKdh2lL69TFrrQpQxEanIJGp4yS35CuoFr4DLj9LNl+s8AZxW+EDLSbGHSCTAttA7elLlt+vuF9tqhEcRFILlffVxIA6xPcJ0i7CN3S7q/dhK4FEOTX735zsBqxangtwk+MgugMPMJUGFdFfMjt6Y7kB79tuqEmtle9nVqk5eRn8gMHNbLo=}
conda_forge_output_validation: true
